Controller・Service・Mapper・SQLの編集
aya030/DateCalculationApp pull request #3
Opened 2022-05-06 02:34 UTC by aya030

先生からのコメントの修正

2022-05-06 07:35 UTC, yoshi-koyama reviewed
@aya030 コメントしました！

2022-05-06 07:35 UTC, yoshi-koyama commented on src/main/java/com/example/demo/repository/DateMapper.java
> +	public DateCalc findById(int id);
存在しない場合を考慮して以下としたいです。
```suggestion
	public Optional<DateCalc> findById(int id);
```

2022-05-06 07:35 UTC, yoshi-koyama commented on src/main/java/com/example/demo/controller/DateController.java
>  		dateService.updateOne(dateCalc.getId(), dateCalc.getDateid(), dateCalc.getName(), dateCalc.getPlusyear(),
このままですと
`@PathVariable("id") int id`
で受け取ったidを使っていないことになりますね。
HTMLのformからidを消すか、パス変数を使わないというようにするのがいいかと思います。

2022-05-06 07:35 UTC, yoshi-koyama commented on src/main/java/com/example/demo/controller/DateController.java
>  		dateService.updateOne(dateCalc.getId(), dateCalc.getDateid(), dateCalc.getName(), dateCalc.getPlusyear(),
また、dateServiceにわたしたidが実はデータベースに存在しない場合、どうするのか？というハンドリングが抜けていますね！

2022-05-06 07:35 UTC, yoshi-koyama commented on src/main/java/com/example/demo/service/DateService.java
>  		}
練習がてら、こちらの結果を作成する処理をStream APIを使って書いてみてください！

2022-05-06 07:36 UTC, yoshi-koyama commented
@aya030 PRの概要に作成いただいたGoogle documentのリンクはっつけておいたらあとでPRから対応内容が追えるのでいいかなと思いました。

2022-05-13 02:27 UTC, YudaiNoda3576 requested changes
気になるところコメントしました！

2022-05-13 02:27 UTC, YudaiNoda3576 commented on src/main/resources/templates/error/404.html
> +</html>
改行が含まれていないようなので、改行を入れましょう！
IDEの設定で保存時に改行を入れるということもできるのでそちら設定してみてください！


InteliJの場合はこんな感じです
![スクリーンショット 2022-05-13 11 25 33](https://user-images.githubusercontent.com/63564761/168199155-1f3e575d-a8a0-4db9-9734-9dd75e87c0ae.png)

2022-05-13 02:27 UTC, YudaiNoda3576 commented on src/main/java/com/example/demo/controller/DateController.java
> +		Optional<DateCalc> date = dateService.findById(id);
Optionalチェック導入してるのいいですね！:smile:

2022-05-13 02:35 UTC, YudaiNoda3576 requested changes
こちらも気になったところコメントさせていただきました！

2022-05-13 02:35 UTC, YudaiNoda3576 commented on src/main/java/com/example/demo/controller/DateController.java
>  }
改行ですね！

2022-05-13 02:35 UTC, YudaiNoda3576 commented on src/main/resources/templates/index.html
> +		<form class="p-index__form" th:action="@{/datecalc/calc}" method="GET">
細かいですが、全体的にアンダーバーが全角になってないですかね？？

2022-05-13 02:35 UTC, YudaiNoda3576 commented on src/main/resources/static/css/style.css
> +.p-index__form {
自分でスタイル当てていくの本当尊敬します笑

2022-05-13 02:35 UTC, YudaiNoda3576 commented on src/main/java/com/example/demo/controller/DateController.java
> +		model.addAttribute("errormessage", "* 日付を入力してください");
Entityクラスにnotblank制約などを付与して、バリデーションをかけているようでしたので、その場合は@Validated などのアノテーションを使うことでより簡単に実現できるのでそちらを試してみてください！

2022-05-13 02:43 UTC, YudaiNoda3576 commented on src/main/java/com/example/demo/service/DateService.java
> +		List<LocalDate> dateCalcResultList = dateCalcs.stream()
いい感じです！実装内容は問題ないかと思います。
細かいところですが、下記のような形でフォーマットを揃えた方が僕は好きです笑

```
 .map(date -> selectedDate.plusYears(date.getPlusyear())
                                         .plusMonths(date.getPlusmonth())
                                         .plusDays(date.getPlusday()))
```

2022-05-13 03:27 UTC, aya030 commented on src/main/resources/templates/index.html
> +		<form class="p-index__form" th:action="@{/datecalc/calc}" method="GET">
こちらアンダーバー2こで統一しております！🙏

2022-05-15 11:42 UTC, aya030 commented on src/main/java/com/example/demo/controller/DateController.java
> +		model.addAttribute("errormessage", "* 日付を入力してください");
#Validatedが上手く行かなかったのでifで分岐させてみました。

2022-05-16 01:09 UTC, YudaiNoda3576 commented on src/main/resources/templates/index.html
> +		<form class="p-index__form" th:action="@{/datecalc/calc}" method="GET">
@aya030 
アンダーバー二個で統一というのはどういった理由でされているのでしょうか？？
僕の不勉強かもなのですがあまり見たことがなく、気になりました！

2022-05-16 01:09 UTC, YudaiNoda3576 commented on src/main/java/com/example/demo/controller/DateController.java
> +		model.addAttribute("errormessage", "* 日付を入力してください");
@aya030 
Validateを使いたいですね！
Controllerクラスに条件分岐のようなロジックを入れるのはアンチパターンになります〜
FatControllerというやつです。
もしどうしてもそういったロジックを入れたい場合は基本メソッドやクラスに切り出すべきかと思います。
そうしないと、講座の後半で実装する自動テストがとても書きづらくなりますし、Controllerクラスの本来の役割から中身が離れてしまって見通しの悪いコードになってしまうからです！（そうなると保守作業［システムをリリースしてから引き続きそのシステムが問題なく動くようにメンテナンスしたり新しい機能を追加したりしていく作業です。作るのは数ヶ月でできますが、その後十年以上システムが稼働することを考えると、この作業が一番の肝で、これをいかにしやすくるかが大事です］のコストがどんどん膨らんで行って悲惨なことになるので頭の片隅に置いておいてください！）

2022-05-16 01:09 UTC, YudaiNoda3576 commented on src/main/java/com/example/demo/controller/DateController.java
> +		if (inputDate == "") {
inputDataのFromクラスはNotNullでValidationがかけられていると思うのですが、
それを踏まえると、ここの条件は空であることを検証するのが適切ですかね？
例えば、画面のinputformにデベロッパーツールで空文字を入力してからsubmitすると登録出来てしまうっていう可能性はないですか？

2022-05-17 06:10 UTC, aya030 commented on src/main/resources/templates/index.html
> +		<form class="p-index__form" th:action="@{/datecalc/calc}" method="GET">
＠YudaiNoda3576
コメントありがとうございます
FLOCSSというCSS設計を採用していて、Block(headerやmainやfooterとか)とElement(imageやwrapperとか)をつなぐ時は、アンダーバー２つで管理するそうです。

こちら参考にしました！
https://yumegori.com/flocss

2022-05-17 06:27 UTC, YudaiNoda3576 commented on src/main/resources/templates/index.html
> +		<form class="p-index__form" th:action="@{/datecalc/calc}" method="GET">
@aya030 
不勉強でした笑
BEMに則って書かれているんですね！
このあたりの命名規則について詳しくはないのですが、こういった規則に則って書いた場合、それっぽい書き方とそれっぽくない書き方が出る可能性があるのでその辺りを含めたレビューが欲しい場合は別途WP・フロントエンドコースのメンター・講師さんにレビュー依頼するとよりその規則に則った命名になっているかをチェックすることが出来るかと思いますので検討してみてください:pray:
http://getbem.com/

2022-05-17 08:03 UTC, YudaiNoda3576 commented on src/main/java/com/example/demo/controller/DateController.java
> +	public String calc(Model model, @Validated @NotBlank @RequestParam("dateinput") String inputDate) {
引数の中に @NotBlankアノテーションをつける実装方法はどこを参考にして実装されましたか？

2022-05-31 18:32 UTC, aya030 commented
inputのバリデーション
[cfaf951](https://github.com/aya030/DateCalculationApp/pull/3/commits/cfaf951e0cba5679e5c42ce779e67b202d9647b6)
＜やったこと＞
inputに日付の値を入れてバリデーションをかける。
・RequestFormの作成(NotBlankのアノテーション付与)
・controller#calcメソッドの引数を(@RequestParam("inputDate") String inputDate, Model model,@Validated @ModelAttribute RequestForm requestForm, BindingResult result)に変更
・if (result.hasErrors()) {}でNull,空白時のエラー分岐
・コントローラーの修正に伴いService#calculationDate(RequestForm requestForm)メソッドの変更
・コントローラーで正しい値を取れるようにindex.htmlのform周りの修正

インデント修正
[2dff78d](https://github.com/aya030/DateCalculationApp/pull/3/commits/2dff78da2aadaaba000d2527d62f8903b042abcf)

2022-06-01 02:52 UTC, yoshi-koyama commented on src/main/java/com/example/demo/form/RequestForm.java
> +	public String inputDate;
publicてフィールド持つのやめておきましょう。
※最近、JavaのセミナーでJavaチャンピオンの谷本さんがフィールドをpublicで持つようにしてると言ってました。が、真意は不明。

2022-06-01 02:52 UTC, yoshi-koyama commented on src/main/java/com/example/demo/controller/DateController.java
> +		dateService.insertOne(dateForm);
今回は対応不要ですがServiceがFormに依存しないように作ってほしいです。

Serviceで扱うのは本来はFormではなく、より業務内容を表現したEntityであってほしい。
またControllerを容易に差し替えられるようなServiceにしておくと変更に強くなります。

この辺りはこのPRでは対応不要ではありますが結構大事なところです。

実装方法についてはまた別のタイミングで相談してくれたら教えます！

2022-06-01 02:52 UTC, yoshi-koyama commented on src/main/java/com/example/demo/controller/DateController.java
> +				dateCalcResultStrList.add(stringDate);
このprでやらなくてもいいですが、streamで書いてみてほしい。

2022-06-01 02:52 UTC, yoshi-koyama commented on src/main/java/com/example/demo/entity/DateCalc.java
>  @Data
idに対するsetterは必要ですか？

2022-06-02 03:54 UTC, aya030 commented
[eaaa872](https://github.com/aya030/DateCalculationApp/pull/3/commits/eaaa8720c3262268610ca8b6ee5330b4efe9bb9d)
ModelAttributeアノテーションを利用して、コントローラーで受け取りたいRequestFormクラスを初期化してreturn。
画面の入力値を受け取れなかったので追加。

[7dd0d84](https://github.com/aya030/DateCalculationApp/pull/3/commits/7dd0d84abc7a5cab709238bc7ac855af2443943a)
RequestFormのフィールドをpublicからprivateで持つように変更。伴い、Serviceクラスの修正。

[88f23ee](https://github.com/aya030/DateCalculationApp/pull/3/commits/88f23ee6319a33ce0ac41ee3d6d9cb7b7a16bfaa)
Controller#calcの変数dateCalcResultStrListをStreamAPIに書き換え

2022-06-14 12:20 UTC, merged